name: Build and Deploy listUser Service

on:
  push:
    paths:
      - 'backend/Inventories/create-inventories/**'
    branches:
      - bd_microservices

  pull_request:
    paths:
      - 'backend/Inventories/create-inventories/**'
    branches:
      - QA
      - main

jobs:
  build-and-push:
    name: ğŸ“¦ Build Docker Image and Push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Clone the repository
        uses: actions/checkout@v3

      - name: ğŸ³ Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: ğŸ› ï¸ Build Docker Image
        run: |
          docker build --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} -t ${{ secrets.DOCKER_USERNAME }}/listUser:latest backend/User/listUser
          docker tag ${{ secrets.DOCKER_USERNAME }}/listUser:latest ${{ secrets.DOCKER_USERNAME }}/listUser:${{ github.sha }}

      - name: ğŸ“¤ Upload image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/listUser:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/listUser:${{ github.sha }}

  deploy-to-ec2:
    name: ğŸš€ Deploy listUser Service on AWS EC2
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: ğŸ”„ Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/listUser:latest
            sudo docker stop listUser || true
            sudo docker rm listUser || true
            sudo docker run -d --name listUser -p 8090:8090 \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              ${{ secrets.DOCKER_USERNAME }}/listUser:latest
          EOF
