name: Build and Deploy listProduct Service

on:
  push:
    paths:
      - 'backend/Products/listProduct/**'
    branches:
      - bd_microservices

  pull_request:
    paths:
      - 'backend/Products/listProduct/**'
    branches:
      - "QA"
      - "main"

jobs:
  build-and-push:
    name: ğŸ“¦ Build Docker Image and Push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Clone the repository
        uses: actions/checkout@v3

      - name: ğŸ³ Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: ğŸ› ï¸ Build Docker Image
        run: |
          docker build --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} -t ${{ secrets.DOCKER_USERNAME }}/listProduct:latest backend/Products/listProduct
          docker tag ${{ secrets.DOCKER_USERNAME }}/listProduct:latest ${{ secrets.DOCKER_USERNAME }}/listProduct:${{ github.sha }}

      - name: ğŸ“¤ Upload image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/listProduct:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/listProduct:${{ github.sha }}

  deploy-to-ec2:
    name: ğŸš€ Deploy listProduct Service on AWS EC2
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: ğŸ”„ Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/listProduct:latest
            sudo docker stop listProduct || true
            sudo docker rm listProduct || true
            sudo docker run -d --name listProduct -p 8081:8081 \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              ${{ secrets.DOCKER_USERNAME }}/listProduct:latest
          EOF
