name: Build and Deploy login Service

on:
  push:
    paths:
      - 'backend/User/login/**'
    branches:
      - bd_microservices

  pull_request:
    paths:
      - 'backend/User/login/**'
    branches:
      - "QA"
      - "main"

jobs:
  build-and-push:
    name: ğŸ“¦ Build Docker Image and Push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Clone the repository
        uses: actions/checkout@v3

      - name: ğŸ³ Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: ğŸ› ï¸ Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/login:latest backend/User/login
          docker tag ${{ secrets.DOCKER_USERNAME }}/login:latest ${{ secrets.DOCKER_USERNAME }}/login:${{ github.sha }}

      - name: ğŸ“¤ Upload image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/login:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/login:${{ github.sha }}

  deploy-to-ec2:
    name: ğŸš€ Deploy login Service on AWS EC2
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: ğŸ”„ Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/login:latest
            sudo docker stop login || true
            sudo docker rm login || true
            sudo docker run -d --name login -p 8092:8092 \
              ${{ secrets.DOCKER_USERNAME }}/login:latest
          EOF
