name: Build and Deploy UpdateCategories Service

on:
  push:
    paths:
      - 'backend/Categories/updateCategories/**'
    branches:
      - bd_microservices

  pull_request:
    paths:
      - 'backend/Categories/updateCategories/**'
    branches:
      - "QA"
      - "main"

jobs:
  build-and-push:
    name: ğŸ“¦ Build Docker Image and Push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Clone the repository
        uses: actions/checkout@v3

      - name: ğŸ³ Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: ğŸ› ï¸ Build Docker Image
        run: |
          docker build --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} -t ${{ secrets.DOCKER_USERNAME }}/updateCategories:latest backend/Categories/updateCategories
          docker tag ${{ secrets.DOCKER_USERNAME }}/updateCategories:latest ${{ secrets.DOCKER_USERNAME }}/updateCategories:${{ github.sha }}

      - name: ğŸ“¤ Upload image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/updateCategories:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/updateCategories:${{ github.sha }}

  deploy-to-ec2:
    name: ğŸš€ Deploy on AWS EC2
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: ğŸ”„ Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/updateCategories:latest
            sudo docker stop updateCategories || true
            sudo docker rm updateCategories || true
            sudo docker run -d --name updateCategories -p 5000:5000 \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              ${{ secrets.DOCKER_USERNAME }}/updateCategories:latest
          EOF
