name: Build and Deploy Update-Inventory Service

on:
  push:
    paths:
      - 'backend/Inventories/update-inventories/**'
    branches:
      - Yamel_inventory

  pull_request:
    paths:
      - 'backend/Inventories/update-inventories/**'
    branches:
      - "QA"
      - "main"

jobs:
  build-and-push:
    name: ğŸ“¦ Build Docker Image and Push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Clone the repository
        uses: actions/checkout@v3

      - name: ğŸ³ Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: ğŸ› ï¸ Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/update-inventory:latest backend/Inventories/update-inventories
          docker tag ${{ secrets.DOCKER_USERNAME }}/update-inventory:latest ${{ secrets.DOCKER_USERNAME }}/update-inventory:${{ github.sha }}

      - name: ğŸ“¤ Upload image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/update-inventory:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/update-inventory:${{ github.sha }}

  deploy-to-ec2:
    name: ğŸš€ Deploy on AWS EC2
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: ğŸ”„ Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/update-inventory:latest
            sudo docker stop update-inventory || true
            sudo docker rm update-inventory || true
            sudo docker run -d --name update-inventory -p 5004:5004 \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              ${{ secrets.DOCKER_USERNAME }}/update-inventory:latest
          EOF
